### PR TITLE
Added styling and components to the studentSession

### PR DESCRIPTION
**Pull request by Mbareck21**
### Arranged the mention session details

- Displayed session start and end times (local times)
- Added avatars and styling to the session attendees - May add student pictures later, if available
- Rearranged the comment section, displaying each writer and their comment bellow with an avatar displaying the writer's initial.
- May add student pictures later, if available
- Moved the review component to the button of the page
- Ready to take suggestions and make changes 
 
image

### CODE REVIEW

**Comment by Miminiverse** [comment]
Hello 
This looks very nice!
Can we add in the date next to time as well?

**Review by secch97 — CHANGES_REQUESTED** [review]
Hey Mohamed! Great job! I really like the overall result. I just wanted to point out some things I would like you to address:

- Is it possible align all sessions list items? See the last two sessions: The alignment breaks if the mentor name length is longer. I would suggest giving a fixed width to each list item's children.
image

- Maybe modifying the layout, style and colors to this would help to match the app's overall style. What do you think?
image

- User needs to strictly click on "Mentor Session" text to be redirected. Why not making all the box clickable?. Also changing that orange to this orange: #C84B31 would help to match the overall style. Changing the date and time text to white color when hovered would help too.

image

- Entering to the mentor session details returns this error on console. Is there a way to get rid of that error?
image

- Is it possible to give these times the same style as the start and end date on student home page?
image
image

- Adding white text would help the text's legibility. Also giving margin to each enrolled student and giving them a white background color would help too.
image

- Changing this orange to this #C84B31 would help to match the app's overall style. Also adding marging to each comment and giving it a white background color would help
image

- Changing this button's color to this: #C84B31 would help match the overall style. I also think that moving it above the enrolled students would make it look better.
image

- Please check that each list item element has a unique key prop
image

**Comment by Mbareck21** [comment]
- Updated the the layout and style of student cohort and Mentor session.
- Addressed all suggested changes in terms of styling.
- fixed the React child issues.
-  The API  - `GET http://localhost:8000/api/v1/session/comment`  `404
Not Found` is probably caused by some routing issues. I didn't want to make changes to the logic before discussing them. Here is one way to fix it:
- on StudentSession frontend Page :
```javascript
const { data } = await axiosPrivate.post(`/session/${sessionId}/comment`
``` 
on session backend rout:
```javascript
router.route('/:sessionId/comment').get(getAllComment).post(createComment);
``` 
- The comment logic is not working well - but I think @Miminiverse is working on it.
- Changed one line from the Loader JSX (from ` handlerFunction: PropTypes.func.isRequired`, to  `handlerFunction: PropTypes.func`. )
-  I will continue making changes as suggested, but wanted to save these changes.
image
image

**Comment by secch97** [comment]
Hi Mohamed, nice job! Just some couple of suggestions: 

- Add a title to the session hours.
- Reduce the margin between these elements and move the review button as suggested:

image

**Review by secch97 — APPROVED** [review]
Looks good to me now

**Pull request merged**
