### PR TITLE
Student view fixes

### PR DESCRIPTION
**Pull request by secch97**
image
image
image
image

- Added state update when a student adds a new comment.
- App now renders avatars, if available, on student pages.
- Added new loading states on Student pages.
- Slight css modifications on student home page and student cohorts and sessions. 
- Added icons with better quality.

### CODE REVIEW

**Comment by Miminiverse** [comment]
Do you know why when the student does not confirm to join a session, it's still showing you're enrolled

**Comment by Mbareck21** [comment]
> Do you know why when the student does not confirm to join a session, it's still showing you're enrolled
It should show you're NOT enrolled. I will check it and fix it this evening after work. Thanks.

**Comment by Miminiverse** [comment]
hi team I fix it in the back end so no worries it should be good, no need to do anything front end. 
If there's issue please try back end with this PR fixUpdateStatus

**Comment by Miminiverse** [comment]
I would suggest leaving the title as Cohort's name + session, not mentor session. Because this will also for Student's leader session.
Other than that all looks amazing love it!

**Comment by secch97** [comment]
> I would suggest leaving the title as Cohort's name + session, not mentor session. Because this will also for Student's leader session. Other than that all looks amazing love it!

image

image

Hi Tam, I followed your suggestion for the title. Also i checked the enrollment status and it now shows what's expected.

**Review by Mbareck21 — APPROVED** [review]
Looks great to me! Thanks for the tremendous improvements.

**Pull request merged**
